### PR TITLE
Change order of call to warm start and reset penalty parameter before solving

### LINKED ISSUE #36: Warm start fails with Gurobi - `OptimizeNotCalled()`
I realised that I hadn't been using the `warm_start` flag, even though this seems like a simple and effective way of speeding up PH. When I try it with Gurobi I get the following error:

```julia
ERROR: OptimizeNotCalled()
Stacktrace:
  [1] _moi_get_result(::MathOptInterface.Utilities.CachingOptimizer{MathOptInterface.AbstractOptimizer, MathOptInterface.Utilities.UniversalFallback{MathOptInterface.Utilities.GenericModel{Float64, MathOptInterface.Utilities.ModelFunctionConstraints{Float64}}}}, ::MathOptInterface.VariablePrimal, ::Vararg{Any, N} where N)
    @ JuMP ~/.julia/packages/JuMP/Xrr7O/src/JuMP.jl:1085
  [2] get(model::Model, attr::MathOptInterface.VariablePrimal, v::VariableRef)
    @ JuMP ~/.julia/packages/JuMP/Xrr7O/src/JuMP.jl:1120
  [3] value(v::VariableRef; result::Int64)
```

This appears to be fixable with the following (will test tomorrow): https://discourse.julialang.org/t/parallel-solves-in-gurobi-jl/9908/8

Might be worth adding to the documentation (assuming it works).

### PR DESCRIPTION
**Pull request by junglegobs**
Fixes #36

Warm start is now called directly after solving a subproblem. I think this may seem a bit weird, but I don't see how it's incorrect (although the last warm start will admittedly be useless). Now warm start works with Gurobi, though I noticed there's no real checks to see if warm start "works", just a check to see if the correct solution is returned. 

Additionally I added a doc string for the return args of `solve`, since I always find myself having to look at the GitHub documentation to remember what's returned.

### CODE REVIEW

File: src/worker.jl [hunk 1]
```diff
@@ -172,12 +172,9 @@ function process_message(msg::Solve,
 
     _execute_subproblem_callbacks(sub, msg.niter, msg.scen)
 
-    if record.warm_start
-        warm_start(sub.problem)
-    end
-
     start = time()
     sts = solve_subproblem(sub.problem)
+    record.warm_start && warm_start(sub.problem)
```
Comment (jmaack24) [inline src/worker.jl:177]: A couple of things here. First warm starting shouldn't be done within the solution timing bracket.  That is you should swap the warm start call and stop time assignment.

Second, this is probably a result of all my experience with confusing C/C++ code but I don't like using `&&` in place of `if` statements.  I find it makes the code harder to follow.

File: src/ProgressiveHedging.jl [hunk 2]
```diff
@@ -147,6 +147,15 @@ Solve the stochastic programming problem described by `tree` and the models crea
 * `worker_assignments::Dict{Int,Set{ScenarioID}}` : Dictionary specifying which scenario subproblems a worker will create and solve. The key values are worker ids as given by Distributed (see `Distributed.workers()`). The user is responsible for ensuring the specified workers exist and that every scenario is assigned to a worker. If no dictionary is given, scenarios are assigned to workers in round robin fashion. Defaults to empty dictionary.
 * `args::Tuple` : Tuple of arguments to pass to `model_cosntructor`. Defaults to (). See also `other_args` and `kwargs`.
 * `kwargs` : Any keyword arguments not specified here that need to be passed to `subproblem_constructor`.  See also `other_args` and `args`.
+
+**Return Arguments**
+
+* `niter` : Number of iterations performed.
+* `abs_res` : Absolute residual (of what?).
```
Comment (jmaack24) [inline src/ProgressiveHedging.jl:154]: The residual is a combination of two things: the first is the squared L^2 norm of movement between the consensus variables from one iteration to the next. The second is the squared L^2 norm of the lack of consensus.  That is, the sum of squares of the differences of the the scenario specific value and the consensus value.  The absolute residual is the square root of the sum of these two quantities divided by the square root of the number of consensus variables to give the whole thing a kind of sample standard deviation look.  The relative residual is then the absolute residual divided by the maximum consensus variable value.  The code for the computation can all be found in the algorithm.jl file.

File: src/ProgressiveHedging.jl [hunk 3]
```diff
@@ -147,6 +147,15 @@ Solve the stochastic programming problem described by `tree` and the models crea
...
+* `rel_res` : Relative residual (of what?).
+* `obj` : Objective value (not including augmented terms?).
```
Comment (jmaack24) [inline src/ProgressiveHedging.jl:156]: Yes.  The PH terms have been removed.

File: src/penalty_parameter_functions.jl [hunk 4]
```diff
@@ -114,7 +114,10 @@ function process_penalty_subproblem(r::ProportionalPenaltyParameter,
 
         if haskey(r.penalties, xhid)
             if !isapprox(r.penalties[xhid], r_value)
-                error("Penalty parameter must match across scenarios. Got $(r.penalties[xhid]) instead of $(penalty) for variable $(name(phd, xhid)). This error likely means the coefficients in the objective function do not match in the scenario subproblems.")
+                error("Penalty parameter must match across scenarios. Got $(r.penalties[xhid]) instead of $(penalty) for variable $(name(phd, xhid)) when processing penalty parameter for scenario $(scid). This error could mean that:
+                    1. The coefficients in the objective function do not match in the scenario subproblems
+                    2. The variable specific penalties were set in the penalty parameter before the call to `PH.solve`."
```
Comment (jmaack24) [inline src/penalty_parameter_functions.jl:119]: The code should actually be able to handle being given the same penalty parameter for multiple solve commands without producing unusual results.

I'll reopen the issue and put this on there too.

**Review by jmaack24 — CHANGES_REQUESTED** [review]
This is actually how I had thought to solve this issue. Good work. A few things to change in the comments. Mostly because I'm rather particular about the use of `&&`.

File: src/ProgressiveHedging.jl (hunk 3 above)
Comment (junglegobs) [reply src/ProgressiveHedging.jl:156]: Hmmm, ok. I ask because I recalculate my total costs based on my variable values after solving with PH, and I noticed that when PH converges `obj` agrees with my recalculated costs, but if it doesn't then there is a disagreement. Any idea why that might be?

File: src/penalty_parameter_functions.jl [hunk 5]
```diff
@@ -266,3 +268,7 @@ end
 function is_variable_dependent(::Type{SEPPenaltyParameter})::Bool
     return true
 end
+
+function reset_penalty_parameter(r::SEPPenaltyParameter)::SEPPenaltyParameter
+    return SEPPenaltyParameter(r.default, Dict{XhatID,Float64}())
+end
```
Comment (jmaack24) [inline src/penalty_parameter_functions.jl:274]: Need end of line

File: src/ProgressiveHedging.jl [hunk 6]
```diff
@@ -179,6 +179,8 @@ function solve(tree::ScenarioTree,
                ) where {R <: AbstractPenaltyParameter}
                
     timo = TimerOutputs.TimerOutput()
+    
+    reset_penalty_parameter(r)
```
Comment (jmaack24) [inline src/ProgressiveHedging.jl]: Perhaps `clear_penalty_parameter` would be a better name

File: src/penalty_parameter_functions.jl [hunk 7]
```diff
@@ -140,6 +137,10 @@ function is_variable_dependent(::Type{ProportionalPenaltyParameter})::Bool
     return true
 end
 
+function reset_penalty_parameter(r::ProportionalPenaltyParameter)::ProportionalPenaltyParameter
```
Comment (jmaack24) [inline src/penalty_parameter_functions.jl:140]: This won't actually fix the problem.  This function needs to go through the internal data structures and delete in entries

File: src/penalty_parameter_functions.jl [hunk 8]
```diff
@@ -164,6 +165,10 @@ function is_variable_dependent(::Type{ScalarPenaltyParameter})::Bool
     return false
 end
 
+function reset_penalty_parameter(r::ScalarPenaltyParameter)::ScalarPenaltyParameter
```
Comment (jmaack24) [inline src/penalty_parameter_functions.jl:168]: I think the best way to go with this is actually to implement
```
function reset_penalty_parameter(r::AbstractPenaltyParameter)
    return # intentional no-op
end
```
and let that handle any case that doesn't need a reset function.

**Review by jmaack24 — CHANGES_REQUESTED** [review]
See comments.

File: src/ProgressiveHedging.jl [hunk 9]
```diff
@@ -180,7 +180,7 @@ function solve(tree::ScenarioTree,
                
     timo = TimerOutputs.TimerOutput()
     
-    reset_penalty_parameter(r)
+    r = reset_penalty_parameter(r)
```
Comment (jmaack24) [inline src/ProgressiveHedging.jl:183]: This makes a copy of the exist data structure.  I'd prefer to reuse the existing one by deleting the needed entries.

Comment (junglegobs) [reply src/ProgressiveHedging.jl]: I changed this because for some reason it wasn't working. I've added a test now to make sure that it does.

File: src/penalty_parameter_functions.jl [hunk 10]
```diff
@@ -83,6 +83,13 @@ function process_penalty_subproblem(r::AbstractPenaltyParameter,
     throw(UnimplementedError("process_penalty_subproblem is unimplemented for penalty parameter of type $(typeof(r))."))
 end
 
+"""
+Resets any mapping of consensus variable ids to penalty parameter values which `r` may have. This avoids potential bugs caused by the same instance of a penalty parameter being used for several calls to `solve`.
+"""
+function reset_penalty_parameter(r::AbstractPenaltyParameter)::Nothing
```
Comment (jmaack24) [inline src/penalty_parameter_functions.jl:89]: Instead of this throwing an error, you can make it the default behavior for the interface. That is have it be
```
function reset_penalty_parameter(r::AbstractPenaltyParameter)::Nothing
    return # intentional no-op
end
```
Then this only needs to be implemented if required.

**Review by jmaack24 — CHANGES_REQUESTED** [review]

**Comment by junglegobs** [comment]
I forgot to test before committing, the tests fail because I didn't change `reset_penalty_parameter` to `reset_penalty_map`.

**Comment by jmaack24** [comment]
> I forgot to test before committing, the tests fail because I didn't change `reset_penalty_parameter` to `reset_penalty_map`.

Already working on fixing it.
